[package]
name = "os"
version = "0.1.0"
authors = ["Tim Whitaker <camp4climber@gmail.com>"]
description = "Library for various os utilities"

repository = "https://github.com/archdaemon/os"
homepage = "https://github.com/archdaemon/os"
license = "MIT"
readme = "README.md"

[dependencies]
